// AUTO-GENERATED by schema/codegen.py from schema/engine.toml. DO NOT EDIT.
#pragma once

#include <cstdint>

using U64 = uint64_t;

enum Color { WHITE = 0, BLACK = 1 };
enum PieceType { PAWN = 0, KNIGHT = 1, BISHOP = 2, ROOK = 3, QUEEN = 4, KING = 5, NO_PIECE = -1 };
enum class TTFlag { EXACT = 0, LOWER = 1, UPPER = 2 };

constexpr int CR_WK = 0b1000;
constexpr int CR_WQ = 0b0100;
constexpr int CR_BK = 0b0010;
constexpr int CR_BQ = 0b0001;
constexpr U64 FULL_BOARD = 0xFFFFFFFFFFFFFFFFULL;
constexpr U64 FILE_A = 0x0101010101010101ULL;
constexpr U64 FILE_H = 0x8080808080808080ULL;
constexpr U64 FILE_AB = 0x0303030303030303ULL;
constexpr U64 FILE_GH = 0xC0C0C0C0C0C0C0C0ULL;
constexpr U64 NOT_FILE_A = 0xFEFEFEFEFEFEFEFEULL;
constexpr U64 NOT_FILE_H = 0x7F7F7F7F7F7F7F7FULL;
constexpr U64 NOT_FILE_AB = 0xFCFCFCFCFCFCFCFCULL;
constexpr U64 NOT_FILE_GH = 0x3F3F3F3F3F3F3F3FULL;
constexpr U64 RANK_1 = 0x00000000000000FFULL;
constexpr U64 RANK_2 = 0x000000000000FF00ULL;
constexpr U64 RANK_7 = 0x00FF000000000000ULL;
constexpr U64 RANK_8 = 0xFF00000000000000ULL;
constexpr const char* STARTPOS_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
constexpr int MAX_PLY = 64;
constexpr int MAX_HISTORY = 16384;
constexpr int QS_DEPTH = 8;
constexpr int ORDER_TT_MOVE = 20000;
constexpr int ORDER_QUEEN_PROMO = 10000;
constexpr int ORDER_PROMO = 9000;
constexpr int ORDER_CAPTURE_BASE = 5000;
constexpr int ORDER_KILLER1 = 4000;
constexpr int ORDER_KILLER2 = 3000;
constexpr double MATE_THRESHOLD = 8000.0;
constexpr double TIME_SAFETY = 0.85;
constexpr double MOVE_OVERHEAD_MS = 20.0;

constexpr double PIECE_VALUES[6] = {1.0, 3.2, 3.3, 5.0, 9.0, 0.0};
constexpr int CP[6] = {100, 320, 330, 500, 900, 0};
constexpr int PASSED_BONUS[8] = {0, 0, 10, 20, 35, 60, 100, 0};
constexpr int PAWN_PST[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
       5,   10,   10,  -20,  -20,   10,   10,    5,
       5,   -5,  -10,    0,    0,  -10,   -5,    5,
       0,    0,    0,   20,   20,    0,    0,    0,
       5,    5,   10,   25,   25,   10,    5,    5,
      10,   10,   20,   30,   30,   20,   10,   10,
      50,   50,   50,   50,   50,   50,   50,   50,
       0,    0,    0,    0,    0,    0,    0,    0,
};
constexpr int KNIGHT_PST[64] = {
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
     -40,  -20,    0,    0,    0,    0,  -20,  -40,
     -30,    0,   10,   15,   15,   10,    0,  -30,
     -30,    5,   15,   20,   20,   15,    5,  -30,
     -30,    0,   15,   20,   20,   15,    0,  -30,
     -30,    5,   10,   15,   15,   10,    5,  -30,
     -40,  -20,    0,    5,    5,    0,  -20,  -40,
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
};
constexpr int BISHOP_PST[64] = {
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,   10,   10,    5,    0,  -10,
     -10,    5,    5,   10,   10,    5,    5,  -10,
     -10,    0,   10,   10,   10,   10,    0,  -10,
     -10,   10,   10,   10,   10,   10,   10,  -10,
     -10,    5,    0,    0,    0,    0,    5,  -10,
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
};
constexpr int ROOK_PST[64] = {
       0,    0,    0,    5,    5,    0,    0,    0,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
       5,   10,   10,   10,   10,   10,   10,    5,
       0,    0,    0,    0,    0,    0,    0,    0,
};
constexpr int QUEEN_PST[64] = {
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,    5,    5,    5,    0,  -10,
      -5,    0,    5,    5,    5,    5,    0,   -5,
       0,    0,    5,    5,    5,    5,    0,   -5,
     -10,    5,    5,    5,    5,    5,    0,  -10,
     -10,    0,    5,    0,    0,    0,    0,  -10,
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
};
constexpr int KING_MG_PST[64] = {
      20,   30,   10,    0,    0,   10,   30,   20,
      20,   20,    0,    0,    0,    0,   20,   20,
     -10,  -20,  -20,  -20,  -20,  -20,  -20,  -10,
     -20,  -30,  -30,  -40,  -40,  -30,  -30,  -20,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
};
constexpr int KING_EG_PST[64] = {
     -50,  -40,  -30,  -20,  -20,  -30,  -40,  -50,
     -30,  -20,  -10,    0,    0,  -10,  -20,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -30,    0,    0,    0,    0,  -30,  -30,
     -50,  -30,  -30,  -30,  -30,  -30,  -30,  -50,
};

constexpr int PROMO_PIECES[4] = {QUEEN, ROOK, BISHOP, KNIGHT};
constexpr const int* PST_MAP[6] = {PAWN_PST, KNIGHT_PST, BISHOP_PST, ROOK_PST, QUEEN_PST, KING_MG_PST};
