// AUTO-GENERATED by schema/codegen.py from schema/engine.toml. DO NOT EDIT.
#![allow(dead_code, clippy::all)]

pub const WHITE: usize = 0;
pub const BLACK: usize = 1;

pub const PAWN: usize = 0;
pub const KNIGHT: usize = 1;
pub const BISHOP: usize = 2;
pub const ROOK: usize = 3;
pub const QUEEN: usize = 4;
pub const KING: usize = 5;

#[rustfmt::skip]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum TTFlag { Exact, Lower, Upper }

pub const CR_WK: i32 = 0b1000;
pub const CR_WQ: i32 = 0b0100;
pub const CR_BK: i32 = 0b0010;
pub const CR_BQ: i32 = 0b0001;
pub const NO_PIECE: i32 = -1;
pub const FULL_BOARD: u64 = 0xFFFF_FFFF_FFFF_FFFF;
pub const FILE_A: u64 = 0x0101_0101_0101_0101;
pub const FILE_H: u64 = 0x8080_8080_8080_8080;
pub const FILE_AB: u64 = 0x0303_0303_0303_0303;
pub const FILE_GH: u64 = 0xC0C0_C0C0_C0C0_C0C0;
pub const NOT_FILE_A: u64 = 0xFEFE_FEFE_FEFE_FEFE;
pub const NOT_FILE_H: u64 = 0x7F7F_7F7F_7F7F_7F7F;
pub const NOT_FILE_AB: u64 = 0xFCFC_FCFC_FCFC_FCFC;
pub const NOT_FILE_GH: u64 = 0x3F3F_3F3F_3F3F_3F3F;
pub const RANK_1: u64 = 0x0000_0000_0000_00FF;
pub const RANK_2: u64 = 0x0000_0000_0000_FF00;
pub const RANK_7: u64 = 0x00FF_0000_0000_0000;
pub const RANK_8: u64 = 0xFF00_0000_0000_0000;
pub const STARTPOS_FEN: &str = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
pub const MAX_PLY: usize = 64;
pub const MAX_HISTORY: i32 = 16384;
pub const QS_DEPTH: i32 = 8;
pub const ORDER_TT_MOVE: i32 = 20000;
pub const ORDER_QUEEN_PROMO: i32 = 10000;
pub const ORDER_PROMO: i32 = 9000;
pub const ORDER_CAPTURE_BASE: i32 = 5000;
pub const ORDER_KILLER1: i32 = 4000;
pub const ORDER_KILLER2: i32 = 3000;
pub const MATE_THRESHOLD: f64 = 8000.0;
pub const TIME_SAFETY: f64 = 0.85;
pub const MOVE_OVERHEAD_MS: f64 = 20.0;

pub const PIECE_VALUES: [f64; 6] = [1.0, 3.2, 3.3, 5.0, 9.0, 0.0];
pub const CP: [i32; 6] = [100, 320, 330, 500, 900, 0];
pub const PASSED_BONUS: [i32; 8] = [0, 0, 10, 20, 35, 60, 100, 0];
#[rustfmt::skip]
pub const PAWN_PST: [i32; 64] = [
       0,    0,    0,    0,    0,    0,    0,    0,
       5,   10,   10,  -20,  -20,   10,   10,    5,
       5,   -5,  -10,    0,    0,  -10,   -5,    5,
       0,    0,    0,   20,   20,    0,    0,    0,
       5,    5,   10,   25,   25,   10,    5,    5,
      10,   10,   20,   30,   30,   20,   10,   10,
      50,   50,   50,   50,   50,   50,   50,   50,
       0,    0,    0,    0,    0,    0,    0,    0,
];
#[rustfmt::skip]
pub const KNIGHT_PST: [i32; 64] = [
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
     -40,  -20,    0,    0,    0,    0,  -20,  -40,
     -30,    0,   10,   15,   15,   10,    0,  -30,
     -30,    5,   15,   20,   20,   15,    5,  -30,
     -30,    0,   15,   20,   20,   15,    0,  -30,
     -30,    5,   10,   15,   15,   10,    5,  -30,
     -40,  -20,    0,    5,    5,    0,  -20,  -40,
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
];
#[rustfmt::skip]
pub const BISHOP_PST: [i32; 64] = [
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,   10,   10,    5,    0,  -10,
     -10,    5,    5,   10,   10,    5,    5,  -10,
     -10,    0,   10,   10,   10,   10,    0,  -10,
     -10,   10,   10,   10,   10,   10,   10,  -10,
     -10,    5,    0,    0,    0,    0,    5,  -10,
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
];
#[rustfmt::skip]
pub const ROOK_PST: [i32; 64] = [
       0,    0,    0,    5,    5,    0,    0,    0,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
       5,   10,   10,   10,   10,   10,   10,    5,
       0,    0,    0,    0,    0,    0,    0,    0,
];
#[rustfmt::skip]
pub const QUEEN_PST: [i32; 64] = [
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,    5,    5,    5,    0,  -10,
      -5,    0,    5,    5,    5,    5,    0,   -5,
       0,    0,    5,    5,    5,    5,    0,   -5,
     -10,    5,    5,    5,    5,    5,    0,  -10,
     -10,    0,    5,    0,    0,    0,    0,  -10,
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
];
#[rustfmt::skip]
pub const KING_MG_PST: [i32; 64] = [
      20,   30,   10,    0,    0,   10,   30,   20,
      20,   20,    0,    0,    0,    0,   20,   20,
     -10,  -20,  -20,  -20,  -20,  -20,  -20,  -10,
     -20,  -30,  -30,  -40,  -40,  -30,  -30,  -20,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
];
#[rustfmt::skip]
pub const KING_EG_PST: [i32; 64] = [
     -50,  -40,  -30,  -20,  -20,  -30,  -40,  -50,
     -30,  -20,  -10,    0,    0,  -10,  -20,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -30,    0,    0,    0,    0,  -30,  -30,
     -50,  -30,  -30,  -30,  -30,  -30,  -30,  -50,
];

pub const PROMO_PIECES: [i32; 4] = [QUEEN as i32, ROOK as i32, BISHOP as i32, KNIGHT as i32];
#[rustfmt::skip]
pub const PST_MAP: [&[i32; 64]; 6] = [&PAWN_PST, &KNIGHT_PST, &BISHOP_PST, &ROOK_PST, &QUEEN_PST, &KING_MG_PST];
