#!/usr/bin/env python3
"""
Render the single-source-of-truth schema (schema/engine.toml) into the per-language
constant files the three engine ports consume:

    python/engine/_generated.py     cpp/src/generated.hpp     rust/src/generated.rs

Usage:
    python3 schema/codegen.py            # (re)write the generated files
    python3 schema/codegen.py --check    # exit 1 if any file is stale (CI / pre-commit)

Only pure data (enums + constant tables) is generated; behavior and the
struct/API/wire-contract notes in engine.toml are reference documentation.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = Path(__file__).resolve().parent / "engine.toml"

PY_OUT = ROOT / "python" / "engine" / "_generated.py"
CPP_OUT = ROOT / "cpp" / "src" / "generated.hpp"
RS_OUT = ROOT / "rust" / "src" / "generated.rs"

BANNER = "AUTO-GENERATED by schema/codegen.py from schema/engine.toml. DO NOT EDIT."

# ── shared value formatting ──────────────────────────────────────────────────


def _fnum(v) -> str:
    """Round-trippable float literal, identical across all three languages."""
    return repr(float(v))


def _u64(value: str) -> int:
    return int(value, 16)


def _hex_plain(v: int) -> str:
    return "0x" + format(v, "016X")


def _hex_grouped(v: int) -> str:
    """Rust style: 0xFFFF_FFFF_FFFF_FFFF (clippy::unreadable_literal-clean)."""
    digits = format(v, "016X")
    return "0x" + "_".join(digits[i : i + 4] for i in range(0, 16, 4))


def _int_lit(scalar) -> str:
    if scalar.get("fmt") == "bin4":
        return "0b" + format(scalar["value"], "04b")
    return str(scalar["value"])


def _rows(values, width: int, per_line: int, indent: str) -> str:
    """Lay numbers out N-per-line, right-aligned, for the array bodies."""
    cells = [f"{v:>{width}}" for v in values]
    lines = [
        indent + ", ".join(cells[i : i + per_line]) + ","
        for i in range(0, len(cells), per_line)
    ]
    return "\n".join(lines)


# ── schema accessors ─────────────────────────────────────────────────────────


def load():
    with open(SCHEMA, "rb") as fh:
        return tomllib.load(fh)


def piece_index(schema) -> dict[str, int]:
    for e in schema["enum"]:
        if e["name"] == "PieceType":
            return {name: val for name, val in e["members"]}
    raise KeyError("PieceType enum missing from schema")


# ── Python emitter ───────────────────────────────────────────────────────────


def render_python(schema) -> str:
    out: list[str] = [f"# {BANNER}", "# ruff: noqa", "from enum import IntEnum", "", ""]

    for e in schema["enum"]:
        out.append(f"class {e['name']}(IntEnum):")
        for name, val in e["members"]:
            out.append(f"    {name} = {val}")
        if e.get("py_methods"):
            out.append("")
            for line in e["py_methods"].strip("\n").splitlines():
                out.append(f"    {line}" if line else "")
        out.extend(["", ""])

    for s in schema["scalar"]:
        if "langs" in s and "python" not in s["langs"]:
            continue
        t = s["type"]
        if t == "str":
            lit = f'"{s["value"]}"'
        elif t == "float":
            lit = _fnum(s["value"])
        elif t == "u64":
            lit = _hex_plain(_u64(s["value"]))
        else:
            lit = _int_lit(s)
        out.append(f"{s['name']} = {lit}")
    out.append("")

    pieces = [name for name, _ in next(e for e in schema["enum"] if e["name"] == "PieceType")["members"]]

    for t in schema["table"]:
        name, kind, elem = t["name"], t["kind"], t["elem"]
        vals = t["values"]
        if kind == "per_piece":
            out.append(f"{name} = {{")
            for piece, v in zip(pieces, vals):
                lit = _fnum(v) if elem == "float" else str(v)
                out.append(f"    PieceType.{piece}: {lit},")
            out.append("}")
        elif kind == "per_square":
            out.append(f"{name} = [")
            out.append(_rows(vals, 4, 8, "    "))
            out.append("]")
        else:  # plain
            body = ", ".join(_fnum(v) if elem == "float" else str(v) for v in vals)
            out.append(f"{name} = [{body}]")
    out.append("")

    for pl in schema.get("piece_list", []):
        body = ", ".join(f"PieceType.{p}" for p in pl["pieces"])
        out.append(f"{pl['name']} = [{body}]")

    for m in schema.get("pst_map", []):
        out.append(f"{m['name']} = {{")
        for piece, table in m["entries"]:
            out.append(f"    PieceType.{piece}: {table},")
        out.append("}")

    return "\n".join(out).rstrip("\n") + "\n"


# ── C++ emitter ──────────────────────────────────────────────────────────────


def render_cpp(schema) -> str:
    out: list[str] = [
        f"// {BANNER}",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "using U64 = uint64_t;",
        "",
    ]

    for e in schema["enum"]:
        members = list(e["members"]) + list(e.get("cpp_extra", []))
        body = ", ".join(f"{name} = {val}" for name, val in members)
        keyword = "enum class" if e.get("cpp_kind") == "enum_class" else "enum"
        out.append(f"{keyword} {e['name']} {{ {body} }};")
    out.append("")

    for s in schema["scalar"]:
        if "langs" in s and "cpp" not in s["langs"]:
            continue
        t = s["type"]
        if t == "str":
            out.append(f'constexpr const char* {s["name"]} = "{s["value"]}";')
        elif t == "float":
            out.append(f"constexpr double {s['name']} = {_fnum(s['value'])};")
        elif t == "u64":
            out.append(f"constexpr U64 {s['name']} = {_hex_plain(_u64(s['value']))}ULL;")
        else:
            out.append(f"constexpr int {s['name']} = {_int_lit(s)};")
    out.append("")

    for t in schema["table"]:
        name, kind, elem = t["name"], t["kind"], t["elem"]
        vals = t["values"]
        ctype = "double" if elem == "float" else "int"
        n = len(vals)
        if kind == "per_square":
            out.append(f"constexpr {ctype} {name}[{n}] = {{")
            out.append(_rows(vals, 4, 8, "    "))
            out.append("};")
        else:  # per_piece / plain -> flat array
            body = ", ".join(_fnum(v) if elem == "float" else str(v) for v in vals)
            out.append(f"constexpr {ctype} {name}[{n}] = {{{body}}};")
    out.append("")

    for pl in schema.get("piece_list", []):
        body = ", ".join(pl["pieces"])
        out.append(f"constexpr int {pl['name']}[{len(pl['pieces'])}] = {{{body}}};")

    for m in schema.get("pst_map", []):
        body = ", ".join(table for _, table in m["entries"])
        out.append(f"constexpr const int* {m['name']}[{len(m['entries'])}] = {{{body}}};")

    return "\n".join(out).rstrip("\n") + "\n"


# ── Rust emitter ─────────────────────────────────────────────────────────────


def _rust_int_type(s) -> str:
    return s.get("rust_type", "i32")


def render_rust(schema) -> str:
    out: list[str] = [
        f"// {BANNER}",
        "#![allow(dead_code, clippy::all)]",
        "",
    ]

    for e in schema["enum"]:
        kind = e.get("rust_kind", "const")
        if kind == "const":
            ctype = e.get("rust_const_type", "usize")
            for name, val in e["members"]:
                out.append(f"pub const {name}: {ctype} = {val};")
            out.append("")
        else:  # real rust enum (e.g. TTFlag)
            out.append("#[rustfmt::skip]")  # keep the variant layout codegen emits
            if e.get("rust_derives"):
                out.append(f"#[derive({', '.join(e['rust_derives'])})]")
            pascal = e.get("rust_variant_case") == "pascal"
            explicit = e.get("rust_explicit_values", True)
            variants = []
            for name, val in e["members"]:
                vname = name.capitalize() if pascal else name
                variants.append(f"{vname} = {val}" if explicit else vname)
            out.append(f"pub enum {e['name']} {{ {', '.join(variants)} }}")
            out.append("")

    for s in schema["scalar"]:
        if "langs" in s and "rust" not in s["langs"]:
            continue
        t = s["type"]
        if t == "str":
            out.append(f'pub const {s["name"]}: &str = "{s["value"]}";')
        elif t == "float":
            out.append(f"pub const {s['name']}: f64 = {_fnum(s['value'])};")
        elif t == "u64":
            out.append(f"pub const {s['name']}: u64 = {_hex_grouped(_u64(s['value']))};")
        else:
            out.append(f"pub const {s['name']}: {_rust_int_type(s)} = {_int_lit(s)};")
    out.append("")

    for t in schema["table"]:
        name, kind, elem = t["name"], t["kind"], t["elem"]
        vals = t["values"]
        rtype = "f64" if elem == "float" else "i32"
        n = len(vals)
        if kind == "per_square":
            out.append("#[rustfmt::skip]")
            out.append(f"pub const {name}: [{rtype}; {n}] = [")
            out.append(_rows(vals, 4, 8, "    "))
            out.append("];")
        else:  # per_piece / plain -> flat array
            body = ", ".join(_fnum(v) if elem == "float" else str(v) for v in vals)
            out.append(f"pub const {name}: [{rtype}; {n}] = [{body}];")
    out.append("")

    for pl in schema.get("piece_list", []):
        body = ", ".join(f"{p} as i32" for p in pl["pieces"])
        out.append(f"pub const {pl['name']}: [i32; {len(pl['pieces'])}] = [{body}];")

    for m in schema.get("pst_map", []):
        body = ", ".join(f"&{table}" for _, table in m["entries"])
        out.append("#[rustfmt::skip]")  # keep on one line regardless of rustfmt width
        out.append(f"pub const {m['name']}: [&[i32; 64]; {len(m['entries'])}] = [{body}];")

    return "\n".join(out).rstrip("\n") + "\n"


# ── driver ───────────────────────────────────────────────────────────────────

TARGETS = [
    (PY_OUT, render_python),
    (CPP_OUT, render_cpp),
    (RS_OUT, render_rust),
]


def main(argv: list[str]) -> int:
    schema = load()
    check = "--check" in argv
    stale: list[str] = []
    for path, render in TARGETS:
        content = render(schema)
        if check:
            current = path.read_text() if path.exists() else None
            if current != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if check and stale:
        print("Stale generated files (run `python3 schema/codegen.py`):", file=sys.stderr)
        for s in stale:
            print(f"  {s}", file=sys.stderr)
        return 1
    if check:
        print("generated files are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
