# AUTO-GENERATED by schema/codegen.py from schema/engine.toml. DO NOT EDIT.
# ruff: noqa
from enum import IntEnum


class Color(IntEnum):
    WHITE = 0
    BLACK = 1

    def opponent(self) -> "Color":
        return Color(1 - self.value)


class PieceType(IntEnum):
    PAWN = 0
    KNIGHT = 1
    BISHOP = 2
    ROOK = 3
    QUEEN = 4
    KING = 5


class TTFlag(IntEnum):
    EXACT = 0
    LOWER = 1
    UPPER = 2


CR_WK = 0b1000
CR_WQ = 0b0100
CR_BK = 0b0010
CR_BQ = 0b0001
FULL_BOARD = 0xFFFFFFFFFFFFFFFF
FILE_A = 0x0101010101010101
FILE_H = 0x8080808080808080
FILE_AB = 0x0303030303030303
FILE_GH = 0xC0C0C0C0C0C0C0C0
NOT_FILE_A = 0xFEFEFEFEFEFEFEFE
NOT_FILE_H = 0x7F7F7F7F7F7F7F7F
NOT_FILE_AB = 0xFCFCFCFCFCFCFCFC
NOT_FILE_GH = 0x3F3F3F3F3F3F3F3F
RANK_1 = 0x00000000000000FF
RANK_2 = 0x000000000000FF00
RANK_7 = 0x00FF000000000000
RANK_8 = 0xFF00000000000000
STARTPOS_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
MAX_PLY = 64
MAX_HISTORY = 16384
QS_DEPTH = 8
ORDER_TT_MOVE = 20000
ORDER_QUEEN_PROMO = 10000
ORDER_PROMO = 9000
ORDER_CAPTURE_BASE = 5000
ORDER_KILLER1 = 4000
ORDER_KILLER2 = 3000
MATE_THRESHOLD = 8000.0
TIME_SAFETY = 0.85
MOVE_OVERHEAD_MS = 20.0

PIECE_VALUES = {
    PieceType.PAWN: 1.0,
    PieceType.KNIGHT: 3.2,
    PieceType.BISHOP: 3.3,
    PieceType.ROOK: 5.0,
    PieceType.QUEEN: 9.0,
    PieceType.KING: 0.0,
}
CP = {
    PieceType.PAWN: 100,
    PieceType.KNIGHT: 320,
    PieceType.BISHOP: 330,
    PieceType.ROOK: 500,
    PieceType.QUEEN: 900,
    PieceType.KING: 0,
}
PASSED_BONUS = [0, 0, 10, 20, 35, 60, 100, 0]
PAWN_PST = [
       0,    0,    0,    0,    0,    0,    0,    0,
       5,   10,   10,  -20,  -20,   10,   10,    5,
       5,   -5,  -10,    0,    0,  -10,   -5,    5,
       0,    0,    0,   20,   20,    0,    0,    0,
       5,    5,   10,   25,   25,   10,    5,    5,
      10,   10,   20,   30,   30,   20,   10,   10,
      50,   50,   50,   50,   50,   50,   50,   50,
       0,    0,    0,    0,    0,    0,    0,    0,
]
KNIGHT_PST = [
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
     -40,  -20,    0,    0,    0,    0,  -20,  -40,
     -30,    0,   10,   15,   15,   10,    0,  -30,
     -30,    5,   15,   20,   20,   15,    5,  -30,
     -30,    0,   15,   20,   20,   15,    0,  -30,
     -30,    5,   10,   15,   15,   10,    5,  -30,
     -40,  -20,    0,    5,    5,    0,  -20,  -40,
     -50,  -40,  -30,  -30,  -30,  -30,  -40,  -50,
]
BISHOP_PST = [
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,   10,   10,    5,    0,  -10,
     -10,    5,    5,   10,   10,    5,    5,  -10,
     -10,    0,   10,   10,   10,   10,    0,  -10,
     -10,   10,   10,   10,   10,   10,   10,  -10,
     -10,    5,    0,    0,    0,    0,    5,  -10,
     -20,  -10,  -10,  -10,  -10,  -10,  -10,  -20,
]
ROOK_PST = [
       0,    0,    0,    5,    5,    0,    0,    0,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
      -5,    0,    0,    0,    0,    0,    0,   -5,
       5,   10,   10,   10,   10,   10,   10,    5,
       0,    0,    0,    0,    0,    0,    0,    0,
]
QUEEN_PST = [
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
     -10,    0,    0,    0,    0,    0,    0,  -10,
     -10,    0,    5,    5,    5,    5,    0,  -10,
      -5,    0,    5,    5,    5,    5,    0,   -5,
       0,    0,    5,    5,    5,    5,    0,   -5,
     -10,    5,    5,    5,    5,    5,    0,  -10,
     -10,    0,    5,    0,    0,    0,    0,  -10,
     -20,  -10,  -10,   -5,   -5,  -10,  -10,  -20,
]
KING_MG_PST = [
      20,   30,   10,    0,    0,   10,   30,   20,
      20,   20,    0,    0,    0,    0,   20,   20,
     -10,  -20,  -20,  -20,  -20,  -20,  -20,  -10,
     -20,  -30,  -30,  -40,  -40,  -30,  -30,  -20,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
     -30,  -40,  -40,  -50,  -50,  -40,  -40,  -30,
]
KING_EG_PST = [
     -50,  -40,  -30,  -20,  -20,  -30,  -40,  -50,
     -30,  -20,  -10,    0,    0,  -10,  -20,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   30,   40,   40,   30,  -10,  -30,
     -30,  -10,   20,   30,   30,   20,  -10,  -30,
     -30,  -30,    0,    0,    0,    0,  -30,  -30,
     -50,  -30,  -30,  -30,  -30,  -30,  -30,  -50,
]

PROMO_PIECES = [PieceType.QUEEN, PieceType.ROOK, PieceType.BISHOP, PieceType.KNIGHT]
PST_MAP = {
    PieceType.PAWN: PAWN_PST,
    PieceType.KNIGHT: KNIGHT_PST,
    PieceType.BISHOP: BISHOP_PST,
    PieceType.ROOK: ROOK_PST,
    PieceType.QUEEN: QUEEN_PST,
    PieceType.KING: KING_MG_PST,
}
